kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: authors-bin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authors-bin
        version: v1
    spec:
      containers:
      - name: authors-bin
        image: image-registry.openshift-image-registry.svc:5000/<projectname>/authors-bin:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:3000/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:3000/health | grep -q authors"]
          initialDelaySeconds: 40
      restartPolicy: Always
---
